import type { Metadata } from "next";
import { Geist, Geist_Mono,Londrina_Shadow } from "next/font/google";
import "./globals.css";
import 'primeicons/primeicons.css'

const londrinaShadow = Londrina_Shadow({
  variable:"--font-londrina-shadow",
  subsets:["latin"],
  weight:"400",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${londrinaShadow.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
